config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  }
  get 'categories/home', to: 'categories#home', as: 'categories_home'


  authenticated :user do
    root 'categories#home', as: :authenticated_root
  end

  unauthenticated do
    root 'categories#index', as: :unauthenticated_root
  end

  resources :categories, only: %i[index home new create destroy] do
    get :home, on: :collection
    resources :transactions, only: %i[index new create]
  end
end

app/views/shared/_navbar.html.erb
<nav role='navigation' class="back-link bg-primary sticky" style="width: 100%; text-align: center; padding: 1rem 0; margin-top: 0;">
  <div class="container">
    <% if back %>
      <% if user_signed_in? && defined?(category) && request.path == category_transactions_path(category_id: category.id) %>
        <%= link_to(home_categories_path(category_id: category.id), class: "btn btn-primary") do %>
          <i class="fas fa-angle-left"></i>
        <% end %>
      <% elsif @title == "Transactions" %>
        <div class="d-flex justify-content-between align-items-center">
          <%= link_to categories_home_path do %>
            <i class="fas fa-arrow-left" style="color: white; font-size: 1.5rem;"></i>
          <% end %>
          <h4 class="" style="text-align: center; color: white;">
            <%= @title %>
          </h4>
          <p></p>
        </div>
      <% elsif @title == "New Category" %>
        <div class="d-flex justify-content-between align-items-center">
          <%= link_to categories_home_path do %>
            <i class="fas fa-arrow-left" style="color: white; font-size: 1.5rem;"></i>
          <% end %>
          <h4 class="" style="text-align: center; color: white;">
            <%= @title %>
          </h4>
          <p></p>
        </div>
      <% elsif @title == "New Transaction" %>
        <div class="d-flex justify-content-between align-items-center">
          <%= link_to category_transactions_path(@category) do %>
            <i class="fas fa-arrow-left" style="color: white; font-size: 1.5rem;"></i>
          <% end %>
          <h4 class="" style="text-align: center; color: white;">
            <%= @title %>
          </h4>
          <p></p>
        </div>
      <% end %>
    <% end %>
  </div>


  <% if @title == "Categories" && request.path == categories_home_path && categories_path %>
        <h4 class="" style="text-align: center; color: white;">
            <%= @title %>
        </h4>
        <div id="menuToggle">
          <input type="checkbox" />
          <span></span>
          <span></span>
          <span></span>
          <ul id="menu">
            <li><a href=""><%= button_to "Sign out", destroy_user_session_path, method: "delete" %></a></li>
          </ul>
        </div>
  <% end %>
</nav>